# Generated by Django 3.1.5 on 2021-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('silder_image', models.ImageField(blank=True, upload_to='slider_img')),
            ],
        ),
        migrations.CreateModel(
            name='TsfAboutSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsf_logo', models.ImageField(blank=True, upload_to='tsf_logo')),
                ('tsf_greeting', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('tsf_phone', models.CharField(blank=True, max_length=255)),
                ('tsf_email', models.EmailField(blank=True, max_length=255)),
                ('tsf_address', models.TextField(blank=True)),
                ('tsf_about', models.TextField(blank=True)),
                ('tsf_president_name', models.CharField(blank=True, max_length=255)),
                ('tsf_president_photo', models.ImageField(blank=True, upload_to='president_photo')),
                ('tsf_president_title', models.CharField(blank=True, max_length=255)),
                ('tsf_secretary_name', models.CharField(blank=True, max_length=255)),
                ('tsf_secretary_photo', models.ImageField(blank=True, upload_to='secretary_photo')),
                ('tsf_secretary_title', models.CharField(blank=True, max_length=255)),
                ('tsf_fb_link', models.URLField(blank=True, max_length=255)),
                ('tsf_twitter_link', models.URLField(blank=True, max_length=255)),
                ('tsf_instagram_link', models.URLField(blank=True, max_length=255)),
                ('tsf_linkdin_link', models.URLField(blank=True, max_length=255)),
                ('tsf_youtube_link', models.URLField(blank=True, max_length=255)),
                ('developer_name', models.CharField(max_length=200)),
                ('developer_address', models.CharField(max_length=250)),
                ('developer_website', models.URLField(blank=True)),
                ('developer_email', models.EmailField(blank=True, max_length=254)),
                ('developer_fb', models.URLField(blank=True)),
                ('developer_youtube', models.URLField(blank=True)),
                ('developer_instagram', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'TSF ABOUT',
            },
        ),
    ]
