# Generated by Django 3.1.5 on 2021-01-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsfaboutsetting',
            name='developer_linkdin',
            field=models.URLField(blank=True),
        ),
    ]
