# Generated by Django 3.1.5 on 2021-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_tsfaboutsetting_developer_linkdin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=200)),
                ('developer_address', models.CharField(max_length=250)),
                ('developer_website', models.URLField(blank=True)),
                ('developer_email', models.EmailField(blank=True, max_length=254)),
                ('developer_fb', models.URLField(blank=True)),
                ('developer_youtube', models.URLField(blank=True)),
                ('developer_instagram', models.URLField(blank=True)),
                ('developer_linkdin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'DEVELOPER INFO',
            },
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_address',
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_email',
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_fb',
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_instagram',
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_linkdin',
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_name',
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_website',
        ),
        migrations.RemoveField(
            model_name='tsfaboutsetting',
            name='developer_youtube',
        ),
    ]
