# Generated by Django 3.1.5 on 2021-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0003_auto_20210322_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsfaboutsetting',
            name='tsf_flag',
            field=models.ImageField(blank=True, upload_to='tsf_flag'),
        ),
    ]
