# Generated by Django 3.1.5 on 2021-03-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0004_tsfaboutsetting_tsf_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerinfo',
            name='co_assistance_fb',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='developerinfo',
            name='co_assistance_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
