# Generated by Django 3.1.5 on 2021-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0005_auto_20210324_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsfaboutsetting',
            name='tsf_president_about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tsfaboutsetting',
            name='tsf_president_secretary',
            field=models.TextField(blank=True),
        ),
    ]
