# Generated by Django 3.1.5 on 2021-03-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0006_auto_20210327_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsfaboutsetting',
            old_name='tsf_president_secretary',
            new_name='tsf_secretary_about',
        ),
    ]
