# Generated by Django 3.1.5 on 2021-03-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0007_auto_20210327_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsfaboutsetting',
            name='tsf_president_photo',
            field=models.ImageField(upload_to='president_photo'),
        ),
        migrations.AlterField(
            model_name='tsfaboutsetting',
            name='tsf_secretary_photo',
            field=models.ImageField(upload_to='secretary_photo'),
        ),
    ]
