# Generated by Django 3.1.5 on 2021-03-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommitteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmember',
            name='memberbranch',
        ),
        migrations.RemoveField(
            model_name='branchmember',
            name='namebranch',
        ),
        migrations.AddField(
            model_name='branchmember',
            name='branch_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_years', to='CommitteApp.branchyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchyear',
            name='branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_names', to='CommitteApp.branchname'),
        ),
    ]
