# Generated by Django 3.1.5 on 2021-03-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommitteApp', '0003_auto_20210327_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='phone',
        ),
    ]
