# Generated by Django 3.1.5 on 2021-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_app', '0002_auto_20210329_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='Gallery'),
        ),
    ]
