# Generated by Django 3.1.5 on 2021-01-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
